server:
  port: 8080

spring:
  application:
    name: msKotlinLearning
  classformat:
    ignore: true
  datasource:
    url: jdbc:mysql://localhost:3306/mskotlin_db?serverTimezone=UTC&useTimezone=true
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect